In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [14]:
f_x = 'x.txt'
f_l = 'l.txt'

x = np.loadtxt(f_x, dtype = int) 
l = np.loadtxt(f_l, dtype = int)
print(x)

[[3 3 3 ... 2 2 2]
 [2 3 3 ... 3 2 3]
 [3 2 2 ... 2 2 2]
 ...
 [2 3 2 ... 3 2 3]
 [2 3 2 ... 3 3 2]
 [3 2 2 ... 2 2 2]]


In [5]:
L = 40 # length of column
w = 5 # width of column

In [18]:
def img_gen(L,w,x,l,ii):
  # L and w are coumn dimensions
  # x and l are files to generate geometry
  # ii  is the column number to be generated
  x = x
  l = l
  img = np.zeros((L,w), dtype = bool)
  img[0,0:w] = 1
  img[-1,0:w] = 1
  
  for jj in range(1,L-1):
    img[jj,x[ii][jj]-l[ii][jj]:x[ii][jj]+l[ii][jj]] = 1
  
  return img

In [19]:
print(x.shape[0])
img = []
for ii in range(0,x.shape[0]):
  img.append(img_gen(L,w,x,l,ii))

25000


In [22]:
img = np.asarray(img)
print(img)
np.save('x.npy',img)

[[[ True  True  True  True  True]
  [False False  True  True False]
  [False False  True  True False]
  ...
  [False  True  True False False]
  [ True  True  True  True False]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [False False  True  True False]
  [False  True  True  True  True]
  ...
  [ True  True  True  True False]
  [False False  True  True False]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [False  True  True False False]
  [False  True  True False False]
  ...
  [False  True  True False False]
  [ True  True  True  True False]
  [ True  True  True  True  True]]

 ...

 [[ True  True  True  True  True]
  [False False  True  True False]
  [False  True  True False False]
  ...
  [ True  True  True  True False]
  [False False  True  True False]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [False False  True  True False]
  [ True  True  True  True False]
  ...
  [False  True  True  True  True]
  [F

In [23]:
print(l.shape[0])
img = []
for ii in range(0,l.shape[0]):
  img.append(img_gen(L,w,x,l,ii))

25000


In [25]:
img = np.asarray(img)
print(img)
np.save('l.npy',img)

[[[ True  True  True  True  True]
  [False False  True  True False]
  [False False  True  True False]
  ...
  [False  True  True False False]
  [ True  True  True  True False]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [False False  True  True False]
  [False  True  True  True  True]
  ...
  [ True  True  True  True False]
  [False False  True  True False]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [False  True  True False False]
  [False  True  True False False]
  ...
  [False  True  True False False]
  [ True  True  True  True False]
  [ True  True  True  True  True]]

 ...

 [[ True  True  True  True  True]
  [False False  True  True False]
  [False  True  True False False]
  ...
  [ True  True  True  True False]
  [False False  True  True False]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [False False  True  True False]
  [ True  True  True  True False]
  ...
  [False  True  True  True  True]
  [F